# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='task name')),
                ('status', models.BooleanField(default=False, verbose_name='status task')),
                ('priority', models.IntegerField(choices=[(0, 'Critique'), (1, 'Important'), (2, 'Mineur')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created task')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated task')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pm_task',
                'ordering': ['created_at'],
            },
        ),
    ]
