from django.shortcuts import render


def index(request):
    # render index.html file generated by angular-cli in dist/index.html
    # NOTE: this works because `dist` folder is part of Django Template dirs (see settings.py)
    return render(request, template_name='client/index.html', context={})
